# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-06 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=64)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10, verbose_name='\u5de5\u53f7')),
                ('employee_name', models.CharField(max_length=20, verbose_name='\u59d3\u540d')),
                ('position', models.CharField(max_length=20, verbose_name='\u804c\u4f4d')),
                ('state', models.CharField(default='\u5728\u804c', max_length=10, verbose_name='\u72b6\u6001')),
                ('username', models.CharField(max_length=20, verbose_name='\u767b\u9646\u8d26\u53f7')),
                ('password', models.CharField(max_length=20, verbose_name='\u5bc6\u7801')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'ordering': ('employee_id',),
                'verbose_name': '\u5458\u5de5\u8868',
                'verbose_name_plural': '\u5458\u5de5\u8868',
            },
        ),
        migrations.CreateModel(
            name='Parkinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_id', models.CharField(max_length=30, verbose_name='\u505c\u8f66\u573aID')),
                ('park_name', models.CharField(max_length=50, verbose_name='\u505c\u8f66\u573a\u540d\u79f0')),
                ('country', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u56fd\u5bb6')),
                ('province', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u7701')),
                ('city', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u5e02')),
                ('district', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u533a')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8be6\u7ec6\u5730\u5740')),
                ('park_type', models.CharField(choices=[('\u4f4f\u5b85', '\u4f4f\u5b85'), ('\u5199\u5b57\u697c', '\u5199\u5b57\u697c'), ('\u5546\u4e1a', '\u5546\u4e1a'), ('\u5546\u4f4f\u6df7\u5408', '\u5546\u4f4f\u6df7\u5408')], default='\u4f4f\u5b85', max_length=20, verbose_name='\u505c\u8f66\u573a\u7c7b\u578b')),
                ('property', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7269\u4e1a\u516c\u53f8')),
                ('Property_contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u505c\u8f66\u573a\u8054\u7cfb\u4eba')),
                ('Property_tele', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8054\u7cfb\u4eba\u7535\u8bdd')),
                ('space_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u8f66\u4f4d\u6570')),
                ('carriage_way', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8fdb\u51fa\u53e3\u6570\u91cf')),
                ('construction_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='\u65bd\u5de5\u65f6\u95f4')),
                ('using_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='\u542f\u7528\u65f6\u95f4')),
                ('watch_man', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u503c\u5b88\u4eba')),
                ('train_man', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u57f9\u8bad\u4eba')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5907\u6ce8')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkmanage.Employee', verbose_name='\u533a\u57df\u8d1f\u8d23\u4eba')),
            ],
            options={
                'ordering': ('park_id',),
                'verbose_name': '\u505c\u8f66\u573a\u5217\u8868',
                'verbose_name_plural': '\u505c\u8f66\u573a\u5217\u8868',
            },
        ),
    ]
