# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-06 12:42
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u5458\u5de5ID')),
                ('user_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u5458\u5de5\u59d3\u540d')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u624b\u673a\u53f7\u7801')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='\u5176\u4ed6')),
                ('state', models.CharField(default=1, max_length=1, verbose_name='\u72b6\u6001')),
                ('account', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u8d26\u53f7')),
                ('password', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5bc6\u7801')),
            ],
            options={
                'verbose_name': '\u7528\u62371',
                'verbose_name_plural': '\u7528\u62371',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u90e8\u95e8\u540d\u79f0')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u90e8\u95e8\u63cf\u8ff0')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u90e8\u95e8',
                'verbose_name_plural': '\u90e8\u95e8',
            },
        ),
        migrations.CreateModel(
            name='UserLoginRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5ba2\u6237\u7aef')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u767b\u5f55\u533a\u57df')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='\u5ba2\u6237\u7aefIP')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_loginrecord', to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u767b\u5f55\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u767b\u5f55\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='UserPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u804c\u4f4d\u540d\u79f0')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u804c\u4f4d\u63cf\u8ff0')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u804c\u4f4d',
                'verbose_name_plural': '\u804c\u4f4d',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_department', to='users.UserDepartment', verbose_name='\u90e8\u95e8'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_position', to='users.UserPosition', verbose_name='\u804c\u4f4d'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
